# .circleci/config.yml
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.0.0"
    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --verbose
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan --formatter xcpretty-json-formatter
          environment:
            SCAN_DEVICE: iPhone X
            SCAN_SCHEME: SwiftGraylog
            XCPRETTY_JSON_FILE_OUTPUT: xcodebuild.json
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
